Update to 0.3.1. See CHANGES.md

diff --git a/bin/arch-bootstrap b/bin/arch-bootstrap
--- a/bin/arch-bootstrap
+++ b/bin/arch-bootstrap
@@ -17,7 +17,7 @@ if [[ -z $ALEXPRO100_LIB_VERSION ]]; then
       echo -e "ALEXPRO100_LIB_LOCATION is not set!"; return 1
     fi
   fi
-  source $ALEXPRO100_LIB_LOCATION
+  source "$ALEXPRO100_LIB_LOCATION"
 fi
 
 # Check options.
@@ -29,19 +29,19 @@ if [[ -z $3 ]]; then
   exit 1
 fi
 
-ERROR="" arch=$1 mirror=$2 
+arch=$1 mirror=$2 
 if [[ $CUSTOM_ARCH_REPO == "1" ]]; then
-  repo=$3; dir=$(realpath -q $4); shift 4
+  repo=$3; dir="$(realpath -q "$4")"; shift 4
 else
-  dir=$(realpath -q $3); shift 3
+  dir="$(realpath -q "$3")"; shift 3
 fi
 install_packages="$@"
 
-parse_arch $(uname -m)
-if [[ $arch == $arch_arch ]]; then
+parse_arch "$(uname -m)"
+if [[ $arch == "$arch_arch" ]]; then
   arch_chroot_command="chroot_rootfs auto"
 else
-  if qemu_chroot check $arch ok; then
+  if qemu_chroot check "$arch" ok; then
     arch_chroot_command="qemu_chroot $arch"
   else
     exit 1
@@ -78,11 +78,11 @@ libssh2 libunistring lz4 mpfr ncurses npth
 openssl pacman pinentry readline sqlite xz zlib zstd)
 
 case $arch in
-  i?86) BASIC_PACKAGES=(archlinux32-keyring archlinux-keyring ${BASIC_PACKAGES[*]})
+  i?86) BASIC_PACKAGES=(archlinux32-keyring archlinux-keyring "${BASIC_PACKAGES[*]}")
   ;;
-  x86_64) BASIC_PACKAGES=(archlinux-keyring ${BASIC_PACKAGES[*]})
+  x86_64) BASIC_PACKAGES=(archlinux-keyring "${BASIC_PACKAGES[*]}")
   ;;
-  *) BASIC_PACKAGES=(archlinuxarm-keyring ${BASIC_PACKAGES[*]})
+  *) BASIC_PACKAGES=(archlinuxarm-keyring "${BASIC_PACKAGES[*]}")
   ;;
 esac
 
@@ -100,7 +100,7 @@ for package in ${BASIC_PACKAGES[*]}; do
   # Download packages.
   if [[ ! -f "${cache_dir}/${pkg_file}" ]]; then
     echo ""
-    get_file_s "${cache_dir}/${pkg_file}" "${core_repo}/${pkg_file}"
+    get_file_s "${cache_dir}/${pkg_file}" "${core_repo}/${pkg_file}" || return_err "Failed to download ${pkg_file}!"
   else
     echo -e "exists!"
   fi
@@ -112,34 +112,33 @@ for package in ${BASIC_PACKAGES[*]}; do
   pkg_file=$(echo "${pkg_list}" | grep -m1 -e "^${package}-[[:digit:]].*\.xz$" -e "^${package}-[[:digit:]].*\.gz$" -e "^${package}-[[:digit:]].*\.zst$")
   # Unpack downloaded packages.
   case "${pkg_file}" in
-    *.gz) tar -xzf "${cache_dir}/${pkg_file}" -C "${arch_tmp}" --exclude='.INSTALL' --exclude='.MTREE' --exclude='.PKGINFO' --exclude='.BUILDINFO' 2>/dev/null;;
-    *.bz2) tar -xjf "${cache_dir}/${pkg_file}" -C "${arch_tmp}" --exclude='.INSTALL' --exclude='.MTREE' --exclude='.PKGINFO' --exclude='.BUILDINFO' 2>/dev/null;;
-    *.xz) tar -xJf "${cache_dir}/${pkg_file}" -C "${arch_tmp}" --exclude='.INSTALL' --exclude='.MTREE' --exclude='.PKGINFO' --exclude='.BUILDINFO' 2>/dev/null;;
-    *.zst) tar --zstd -xf "${cache_dir}/${pkg_file}" -C "${arch_tmp}" --exclude='.INSTALL' --exclude='.MTREE' --exclude='.PKGINFO' --exclude='.BUILDINFO' 2>/dev/null;;
+    *.gz) tar -xzf "${cache_dir}/${pkg_file}" -C "${arch_tmp}" --exclude='.INSTALL' --exclude='.MTREE' --exclude='.PKGINFO' --exclude='.BUILDINFO' 2>/dev/null || msg_print error "Failed extraction ${pkg_file}!";;
+    *.bz2) tar -xjf "${cache_dir}/${pkg_file}" -C "${arch_tmp}" --exclude='.INSTALL' --exclude='.MTREE' --exclude='.PKGINFO' --exclude='.BUILDINFO' 2>/dev/null || msg_print error "Failed extraction ${pkg_file}!";;
+    *.xz) tar -xJf "${cache_dir}/${pkg_file}" -C "${arch_tmp}" --exclude='.INSTALL' --exclude='.MTREE' --exclude='.PKGINFO' --exclude='.BUILDINFO' 2>/dev/null || msg_print error "Failed extraction ${pkg_file}!";;
+    *.zst) tar --zstd -xf "${cache_dir}/${pkg_file}" -C "${arch_tmp}" --exclude='.INSTALL' --exclude='.MTREE' --exclude='.PKGINFO' --exclude='.BUILDINFO' 2>/dev/null || msg_print error "Failed extraction ${pkg_file}!";;
     *) return_err "Incorrect ${pkg_file}! Exiting...";;
   esac
 done
 
-exit 1
 msg_print note "Preparing tempory rootfs..."
-mkdir -p $arch_tmp/etc/pacman.d
-[[ $CUSTOM_ARCH_REPO != "1" ]] && echo "Server = $repo" >> $arch_tmp/etc/pacman.d/mirrorlist
+mkdir -p "$arch_tmp/etc/pacman.d"
+[[ $CUSTOM_ARCH_REPO != "1" ]] && echo "Server = $repo" >> "$arch_tmp/etc/pacman.d/mirrorlist"
 if [[ $CUSTOM_ARCH_REPO == "1" ]]; then
-  sed -i 's|SigLevel    = Required DatabaseOptional|SigLevel = Never|;s|Include = /etc/pacman.d/mirrorlist||;s|\[core\]||;s|\[extra\]||;s|\[community\]||' $arch_tmp/etc/pacman.conf
-  echo -e "[$repo]\nServer = $mirror" >> $arch_tmp/etc/pacman.conf
+  sed -i 's|SigLevel    = Required DatabaseOptional|SigLevel = Never|;s|Include = /etc/pacman.d/mirrorlist||;s|\[core\]||;s|\[extra\]||;s|\[community\]||' "$arch_tmp/etc/pacman.conf"
+  echo -e "[$repo]\nServer = $mirror" >> "$arch_tmp/etc/pacman.conf"
 fi
-echo -e "update-ca-trust\npacman-key --init\npacman-key --populate\ncp -a {,/mnt}/etc/pacman.d/gnupg" >> $arch_tmp/root/run.sh
-echo "pacman -r /mnt --cachedir /mnt/var/cache/pacman/pkg --noconfirm -Sy base $install_packages" >> $arch_tmp/root/run.sh
-chmod +x $arch_tmp/root/run.sh
+echo -e "update-ca-trust\npacman-key --init\npacman-key --populate\ncp -a {,/mnt}/etc/pacman.d/gnupg" >> "$arch_tmp/root/run.sh"
+echo "pacman -r /mnt --cachedir /mnt/var/cache/pacman/pkg --noconfirm -Sy base $install_packages" >> "$arch_tmp/root/run.sh"
+chmod +x "$arch_tmp/root/run.sh"
 
 msg_print note "Installing to choosed directory..."
-mkdir -m 0755 -p "$dir"/var/{lib/pacman,log} "$dir"/{dev,run,etc/pacman.d}
-mkdir -m 1777 -p "$dir"/tmp
-mkdir -m 0555 -p "$dir"/{sys,proc}
+mkdir -m 0755 "$dir/var/lib" "$dir/var/lib/pacman" "$dir/log" "$dir/dev" "$dir/run" "$dir/etc" "$dir/etc/pacman.d"
+mkdir -m 1777 "$dir/tmp"
+mkdir -m 0555 "$dir/sys" "$dir/proc"
 ROOTFS_DIR_NO_FIX=1
 chroot_add_mount dir "$dir" "$arch_tmp/mnt" --rbind --make-rslave
 chroot_setup "$arch_tmp/mnt"
-$arch_chroot_command $arch_tmp /bin/bash /root/run.sh
+$arch_chroot_command "$arch_tmp" /bin/bash /root/run.sh
 rm -rf "$arch_tmp"
 mv "$dir"/etc/resolv.conf{.pacnew,} || :
 mv "$dir"/etc/hosts{.pacnew,} || :
