FIX: Make init less heavy.

diff --git a/bin/make_images/linux_install_files/init b/bin/make_images/linux_install_files/init
--- a/bin/make_images/linux_install_files/init
+++ b/bin/make_images/linux_install_files/init
@@ -1,9 +1,9 @@
-#!/bin/sh
-
+#!/bin/busybox ash
+# shellcheck shell=dash
 
 # Edited to boot squashfs
 # Taken most parts from original init
-VERSION=3.5.0-r0
+VERSION=0.1.2 #based on alpine init 3.5.0-r0
 sysroot=/sysroot
 repofile=/tmp/repositories
 
@@ -11,6 +11,8 @@ if [ -z "$rootfs_net" ]; then
 	echo "Executing /init_orig..."
 	exec /init_orig
 fi
+
+quiet=${quiet:-no}
 
 # some helpers
 ebegin() {
@@ -20,7 +22,6 @@ ebegin() {
 	echo -n " * $last_emsg: "
 }
 eend() {
-	local msg
 	if [ "$1" = 0 ] || [ $# -lt 1 ] ; then
 		echo "$last_emsg: ok." > /dev/kmsg
 		[ "$quiet" = yes ] && return 0
@@ -36,22 +37,26 @@ eend() {
 		/bin/busybox sh
 	fi
 }
+return_err() {
+	echo "$*"
+	return 1
+}
 
 # determine the default interface to use if ip=dhcp is set
 # uses the first "eth" interface with operstate 'up'.
 ip_choose_if() {
 	if [ -n "$BOOTIF" ]; then
 		mac=$(printf "%s\n" "$BOOTIF"|sed 's/^01-//;s/-/:/g')
-		dev=$(grep -l $mac /sys/class/net/*/address|head -n 1)
+		dev=$(grep -l "$mac" /sys/class/net/*/address|head -n 1)
 		dev=${dev%/*}
 		[ -n "$dev" ] && echo "${dev##*/}" && return
 	fi
 	for x in /sys/class/net/eth*; do
-		if grep -iq up $x/operstate;then
-			[ -e "$x" ] && echo ${x##*/} && return
+		if grep -iq up "$x/operstate"; then
+			[ -e "$x" ] && echo "${x##*/}" && return
 		fi
 	done
-	[ -e "$x" ] && echo ${x##*/} && return
+	[ -e "$x" ] && echo "${x##*/}" && return
 }
 
 # if "ip=dhcp" is specified on the command line, we obtain an IP address
@@ -76,17 +81,9 @@ ip_choose_if() {
 configure_ip() {
 	[ -n "$MAC_ADDRESS" ] && return
 
-	local IFS=':'
-	set -- ${ip:-dhcp}
-	unset IFS
+	IFS=':' set -- "${ip:-dhcp}"
 
-	local client_ip="$1"
-	local gw_ip="$3"
-	local netmask="$4"
-	local device="$6"
-	local autoconf="$7"
-	local dns1="$8"
-	local dns2="$9"
+	local client_ip="$1" gw_ip="$3" netmask="$4" device="$6" autoconf="$7" dns1="$8" dns2="$9"
 
 	case "$client_ip" in
 		off|none) return;;
@@ -95,24 +92,18 @@ configure_ip() {
 
 	[ -n "$device" ] || device=$(ip_choose_if)
 
-	if [ -z "$device" ]; then
-		echo "ERROR: IP requested but no network device was found"
-		return 1
-	fi
+	[ -z "$device" ] && return_err "ERROR: IP requested but no network device was found"
 
 	if [ "$autoconf" = "dhcp" ]; then
 		# automatic configuration
-		if [ ! -e /usr/share/udhcpc/default.script ]; then
-			echo "ERROR: DHCP requested but not present in initrd"
-			return 1
-		fi
+		[ ! -e /usr/share/udhcpc/default.script ] && return_err "ERROR: DHCP requested but not present in initrd"
 		ebegin "Obtaining IP via DHCP ($device)"
 		ifconfig "$device" 0.0.0.0
 		udhcpc -i "$device" -f -q
 		eend $?
 	else
 		# manual configuration
-		[ -n "$client_ip" -a -n "$netmask" ] || return
+		[ -n "$client_ip" ] && [ -n "$netmask" ] || return
 		ebegin "Setting IP ($device)"
 		if ifconfig "$device" "$client_ip" netmask "$netmask"; then
 			[ -z "$gw_ip" ] || ip route add 0.0.0.0/0 via "$gw_ip" dev "$device"
@@ -125,10 +116,9 @@ configure_ip() {
 		echo "nameserver $i" >> /etc/resolv.conf
 	done
 
-	MAC_ADDRESS=$(cat /sys/class/net/$device/address)
+	MAC_ADDRESS=$(cat "/sys/class/net/$device/address")
 }
 
-# This is used to predict if network access will be necessary
 is_url() {
 	case "$1" in
 	http://*|https://*|ftp://*)
@@ -139,48 +129,27 @@ is_url() {
 }
 
 /bin/busybox mkdir -p /usr/bin /usr/sbin /proc /sys /dev $sysroot
-
-# Spread out busybox symlinks and make them available without full path
 /bin/busybox --install -s
 export PATH=/usr/bin:/bin:/usr/sbin:/sbin
-
-# Make sure /dev/null is a device node. If /dev/null does not exist yet, the command
-# mounting the devtmpfs will create it implicitly as an file with the "2>" redirection.
-# The -c check is required to deal with initramfs with pre-seeded device nodes without
-# error message.
 [ -c /dev/null ] || mknod -m 666 /dev/null c 1 3
-
 mount -t sysfs -o noexec,nosuid,nodev sysfs /sys
 mount -t devtmpfs -o exec,nosuid,mode=0755,size=2M devtmpfs /dev 2>/dev/null \
 	|| mount -t tmpfs -o exec,nosuid,mode=0755,size=2M tmpfs /dev
-
-# Make sure /dev/kmsg is a device node. Writing to /dev/kmsg allows the use of the
-# earlyprintk kernel option to monitor early init progress. As above, the -c check
-# prevents an error if the device node has already been seeded.
 [ -c /dev/kmsg ] || mknod -m 660 /dev/kmsg c 1 11
-
 mount -t proc -o noexec,nosuid,nodev proc /proc
-# pty device nodes (later system will need it)
 [ -c /dev/ptmx ] || mknod -m 666 /dev/ptmx c 5 2
 [ -d /dev/pts ] || mkdir -m 755 /dev/pts
 mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /dev/pts
-
-# shared memory area (later system will need it)
 [ -d /dev/shm ] || mkdir /dev/shm
 mount -t tmpfs -o nodev,nosuid,noexec shm /dev/shm
-
-# read the kernel options. we need surve things like:
-# acpi_osi="!Windows 2006" xen-pciback.hide=(01:00.0)
-set -- $(cat /proc/cmdline)
-
+set -- "$(cat /proc/cmdline)"
 echo "Linux_install Init $VERSION"
 
-# load available drivers to get access to modloop media
+# load available drivers for normal work
 ebegin "Loading boot drivers"
-modprobe -a $(echo "$rootfstype" | tr ',' ' ' ) loop squashfs 2> /dev/null
+modprobe -a "$(echo "${rootfstype:-}" | tr ',' ' ' )" loop squashfs 2> /dev/null
 eend 0
 
-# zpool reports /dev/zfs missing if it can't read /etc/mtab
 ln -s /proc/mounts /etc/mtab
 
 # --CUSTOM LINES
@@ -191,7 +160,7 @@ mkdir -p $overlayfs/root-ro $overlayfs/root-rw/root $overlayfs/root-rw/work
 
 if is_url "$rootfs_net"; then
     nlplug-findfs -p /sbin/mdev -n
-    configure_ip
+    configure_ip || echo "Failed to setup network."
 	echo "Downloading rootfs"
 	wget -O $overlayfs/root-rw/squashfs.img "$rootfs_net"
 	ebegin "Mounting rootfs"
@@ -205,30 +174,31 @@ else
 	nlplug-findfs -p /sbin/mdev \
 		-b $repofile -a /tmp/apkovls
 	repo_dir=$(head -n 1 $repofile)
-	if [ -f $repo_dir/$rootfs_net ]; then
-		mount -o loop,ro $repo_dir/$rootfs_net $overlayfs/root-ro
+	if [ -f "$repo_dir/$rootfs_net" ]; then
+		mount -o loop,ro "$repo_dir/$rootfs_net" $overlayfs/root-ro
 		mount -t overlay -o lowerdir=$overlayfs/root-ro,upperdir=$overlayfs/root-rw/root,workdir=$overlayfs/root-rw/work LIVE_OS $sysroot
 	fi
 	eend $?
 fi
-: ${init:=/sbin/init}
+: "${init:=/sbin/init}"
 if [ -f $sysroot/$init ]; then
 	if [ -f /etc/resolv.conf ]; then
 		cp /etc/resolv.conf $sysroot/etc/resolv.conf
 	fi
-	cat /proc/mounts | while read DEV DIR TYPE OPTS ; do
-		if [ "$DIR" != "/" -a "$DIR" != "$sysroot" -a -d "$DIR" ]; then
-			mkdir -p $sysroot/$DIR
-			mount -o move $DIR $sysroot/$DIR
+	#shellcheck disable=SC2034
+	while read -r DEV DIR TYPE OPTS; do
+		if [ "$DIR" != "/" ] && [ "$DIR" != "$sysroot" ] && [ -d "$DIR" ]; then
+			mkdir -p "$sysroot/$DIR"
+			mount -o move "$DIR" "$sysroot/$DIR"
 		fi
-	done
+	done < /proc/mounts
 	sync
-	exec /bin/busybox switch_root $sysroot $init $(cat $sysroot/proc/cmdline)
+	exec /bin/busybox switch_root $sysroot $init "$(cat $sysroot/proc/cmdline)"
 else
     echo "File $sysroot/$init does not exist!"
 fi
 
 
 echo "initramfs emergency recovery shell launched"
-exec /bin/busybox sh
+/bin/busybox sh
 reboot
